repos:
  - repo: local
    hooks:
      - id: autoflake-remove-unused-variables
        name: autoflake-remove-unused-variables
        types: [python]
        require_serial: true
        language: script
        entry: backend/.venv/bin/python -m autoflake -r --in-place --remove-unused-variables

  - repo: local
    hooks:
      - id: autoflake-remove-all-unused-imports
        name: autoflake-remove-all-unused-imports
        types: [python]
        require_serial: true
        language: script
        entry: backend/.venv/bin/python -m autoflake -r --in-place --remove-all-unused-imports --exclude=__init__.py

  - repo: local
    hooks:
      - id: bandit
        name: bandit
        types: [python]
        require_serial: true
        language: script
        entry: backend/.venv/bin/python -m bandit --recursive --configfile backend/pyproject.toml
        exclude: tests

  - repo: local
    hooks:
      - id: black
        name: black
        types: [python]
        require_serial: true
        language: script
        entry: backend/.venv/bin/python -m black --config backend/pyproject.toml

  - repo: local
    hooks:
      - id: flake8
        name: flake8
        types: [python]
        require_serial: true
        language: script
        entry: backend/.venv/bin/python -m flake8 --toml-config backend/pyproject.toml

  - repo: local
    hooks:
      - id: isort
        name: isort
        types: [python]
        require_serial: true
        language: script
        entry: backend/.venv/bin/python -m isort --settings-path backend/pyproject.toml

  - repo: local
    hooks:
      - id: mypy
        name: mypy
        types: [python]
        require_serial: true
        language: script
        entry: backend/.venv/bin/python -m mypy --config-file backend/pyproject.toml
        exclude: tests

  - repo: local
    hooks:
      - id: prettier
        name: prettier
        files: ^frontend/.*\.(js|jsx|ts|tsx|css|html)$
        require_serial: true
        language: script
        entry: ./frontend/lint.sh

  - repo: https://github.com/pre-commit/pre-commit-hooks # Some out-of-the-box hooks for pre-commit
    rev: "v5.0.0"
    hooks:
      - id: check-yaml # This hook checks yaml files for parseable syntax
      - id: end-of-file-fixer # Ensures that a file is either empty, or ends with one newline
        exclude: requirements*.txt
      - id: trailing-whitespace # This hook trims trailing whitespace
