# Generated by Django 5.1.6 on 2025-02-27 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="gamestate",
            name="over",
            field=models.BooleanField(default=False),
        ),
    ]
