# Generated by Django 5.1.6 on 2025-02-27 05:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0002_gamestate_over"),
    ]

    operations = [
        migrations.AddField(
            model_name="gamestate",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="gamestate",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
