# Generated by Django 5.1.6 on 2025-02-27 06:30

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0003_gamestate_created_at_gamestate_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="gamestate",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
